"""Add

Revision ID: 52e3b7f37311
Revises: 16fdac6f7c3e
Create Date: 2024-11-20 23:48:42.070627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e3b7f37311'
down_revision: Union[str, None] = '16fdac6f7c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('contract', sa.Column(
        'signet_datetime', sa.DateTime(), nullable=True))

    op.execute(
        "UPDATE contract SET signet_datetime = CURRENT_TIMESTAMP WHERE signet_datetime IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'signet_datetime')
    # ### end Alembic commands ###
